CREATE DATABASE BOOKMYMOVIE;
USE  BOOKMYMOVIE;

CREATE TABLE BOOKINGS (
MOVIE_NAME VARCHAR(100),
SCREEN VARCHAR(10),
ROW_NUM VARCHAR(1),
COL_NUM INTEGER(2),
PRICE INTEGER(2),
SEAT_STATUS VARCHAR(1),
USER VARCHAR(26)
);

CREATE TABLE USER (
NAME VARCHAR(26),
GENDER VARCHAR(1),
AGE INTEGER(3),
PHONE_NO INTEGER(15)
);